name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django_job:
    uses: mcxcr/Django-Ads/.github/workflows/test-django.yaml@main
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      CLUSTER_NAME: cr4e-stage
      # DJANGO_SECRET_KEY: test-key-not-good-make-one-way-better-soon

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install DO doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN_KEY }}
    - name: Login to DO Container Registry with short-lived creds
      run: doctl registry login --expiry-seconds 1200
    - name: Build container image
      working-directory: ./web
      run: |
        docker buildx build --platform linux/amd64 -f Dockerfile \
          -t registry.digitalocean.com/cr4e-stage/django-stage-web:latest \
          -t registry.digitalocean.com/cr4e-stage/django-stage-web:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
          .
    - name: Push image
      run: |
        docker push registry.digitalocean.com/cr4e-stage/django-stage-web --all-tags
    - name: K8s cluster kubeconfig file with short-lived creds
      run: |
        doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
    # - name: Update Deployment Secrets
    #   run: |
    #     cat << EOF >> web/.env.prod
    #     AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
    #     DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
    #     DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}
    #     DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
    #     ENV_ALLOWED_HOST=${{ secrets.ENV_ALLOWED_HOST }}
    #     POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
    #     POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
    #     POSTGRES_DB=${{ secrets.POSTGRES_DB }}
    #     POSTGRES_USER=${{ secrets.POSTGRES_USER }}
    #     POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
    #     EOF
    #     kubectl delete secret django-stage-web-prod-env
    #     kubectl create secret generic django-stage-web-prod-env --from-env-file=web/.env.prod
    - name: Update Deployment Image
      run: |
        kubectl set image deployment/django-stage-web-deployment django-stage-web=registry.digitalocean.com/cr4e-stage/django-stage-web:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
    - name: Wait for rollout to finish
      run: |
        kubectl rollout status deployment/django-stage-web-deployment
    - name: Post-Build Django Commands - Migrate / Collectstatic
      run: |
        export SINGLE_POD_NAME=$(kubectl get pod -l app=django-stage-web-deployment -o jsonpath="{.items[0].metadata.name}")
        kubectl exec -it $SINGLE_POD_NAME -- bash /app/migrate.sh
